from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils import timezone

# Create your models here.
class Class(models.Model):
    ''' To create a full class '''
    class_name = models.CharField(max_length=50, help_text="Class Name")
    slug = models.CharField(max_length=settings.TIME_LOG_PAGE_TITLE_MAX_LENGTH, blank=True, editable=False,
                            help_text="Unique URL path to access this page. Generated by the system.")
    class_description = models.TextField(help_text="Enter Class Description Here.")
    class_start_date = models.DateTimeField('Start Date')
    class_end_date = models.DateTimeField('End Date')
    modified = models.DateTimeField(auto_now=True,
                                    help_text="The date and time this page was updated. Automatically generated when the model updates.")
    def __str__(self):
        return self.class_name
    
    def get_absolute_url(self):
        """ Returns a fully-qualified path for a page (/my-new-class-page). """
        path_components = {'slug': self.slug}
        return reverse('detail-page', kwargs=path_components)

    def save(self, *args, **kwargs):
        """ Creates a URL safe slug automatically when a new a class is created. """
        if not self.pk:
            self.slug = slugify(self.class_name, allow_unicode=True)

        # Call save on the superclass.
        return super(Class, self).save(*args, **kwargs)
