# Generated by Django 3.0.2 on 2020-03-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('class_description', models.CharField(max_length=200)),
                ('class_start_date', models.DateTimeField(verbose_name='Start Date')),
                ('class_end_date', models.DateTimeField(verbose_name='End Date')),
            ],
        ),
    ]
