# Generated by Django 3.0.2 on 2020-03-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeLog', '0002_auto_20200305_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text='Unique URL path to access this page. Generated by the system.', max_length=600),
        ),
    ]
